#!/usr/bin/env python3
"""
Skill Library — FTS5-powered fast skill retrieval for SOV3.
Hermes-inspired: 10ms query time over 10K entries.
Skills are auto-generated by the Reflection Engine and validated by BFT council.
"""
import sqlite3
import json
import hashlib
from datetime import datetime
from typing import Dict, Any, List, Optional

DB_PATH = "data/skill_library.db"


class SkillLibrary:
    """
    Persistent skill storage with full-text search.
    """

    def __init__(self, db_path: str = DB_PATH):
        self.db_path = db_path
        self._init_db()

    def _init_db(self):
        import os
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        conn = sqlite3.connect(self.db_path)
        # Main skills table
        conn.execute("""
            CREATE TABLE IF NOT EXISTS skills (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                skill_hash TEXT UNIQUE NOT NULL,
                task_type TEXT NOT NULL,
                title TEXT NOT NULL,
                description TEXT NOT NULL,
                yaml_body TEXT NOT NULL,
                care_score REAL,
                usage_count INTEGER DEFAULT 0,
                validated INTEGER DEFAULT 0,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
        """)
        # FTS5 virtual table for fast search
        conn.execute("""
            CREATE VIRTUAL TABLE IF NOT EXISTS skill_search USING fts5(
                title, description, yaml_body,
                content='skills',
                content_rowid='id'
            )
        """)
        # Triggers to keep FTS5 index in sync
        conn.execute("""
            CREATE TRIGGER IF NOT EXISTS skills_ai AFTER INSERT ON skills BEGIN
                INSERT INTO skill_search(rowid, title, description, yaml_body)
                VALUES (new.id, new.title, new.description, new.yaml_body);
            END
        """)
        conn.execute("""
            CREATE TRIGGER IF NOT EXISTS skills_ad AFTER DELETE ON skills BEGIN
                INSERT INTO skill_search(skill_search, rowid, title, description, yaml_body)
                VALUES ('delete', old.id, old.title, old.description, old.yaml_body);
            END
        """)
        conn.execute("""
            CREATE TRIGGER IF NOT EXISTS skills_au AFTER UPDATE ON skills BEGIN
                INSERT INTO skill_search(skill_search, rowid, title, description, yaml_body)
                VALUES ('delete', old.id, old.title, old.description, old.yaml_body);
                INSERT INTO skill_search(rowid, title, description, yaml_body)
                VALUES (new.id, new.title, new.description, new.yaml_body);
            END
        """)
        conn.commit()
        conn.close()

    def ingest(self, skill_hash: str, task_type: str, title: str, description: str,
               yaml_body: str, care_score: float = 0.8) -> bool:
        """Add a new skill to the library. Returns True if new, False if duplicate."""
        conn = sqlite3.connect(self.db_path)
        try:
            conn.execute(
                """
                INSERT INTO skills (skill_hash, task_type, title, description, yaml_body,
                                    care_score, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (skill_hash, task_type, title, description, yaml_body, care_score,
                 datetime.utcnow().isoformat(), datetime.utcnow().isoformat()),
            )
            conn.commit()
            return True
        except sqlite3.IntegrityError:
            return False
        finally:
            conn.close()

    def search(self, query: str, limit: int = 5) -> List[Dict[str, Any]]:
        """FTS5 search over skills. Typical query time: <10ms for 10K entries."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            """
            SELECT s.* FROM skill_search ss
            JOIN skills s ON s.id = ss.rowid
            WHERE skill_search MATCH ?
            ORDER BY rank
            LIMIT ?
            """,
            (query, limit),
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]

    def get_by_task_type(self, task_type: str, limit: int = 5) -> List[Dict[str, Any]]:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            """
            SELECT * FROM skills
            WHERE task_type = ? AND validated = 1
            ORDER BY care_score DESC, usage_count DESC
            LIMIT ?
            """,
            (task_type, limit),
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]

    def validate_skill(self, skill_hash: str) -> bool:
        """Mark a skill as BFT-validated."""
        conn = sqlite3.connect(self.db_path)
        cur = conn.execute(
            "UPDATE skills SET validated = 1, updated_at = ? WHERE skill_hash = ?",
            (datetime.utcnow().isoformat(), skill_hash),
        )
        conn.commit()
        conn.close()
        return cur.rowcount > 0

    def increment_usage(self, skill_hash: str):
        conn = sqlite3.connect(self.db_path)
        conn.execute(
            "UPDATE skills SET usage_count = usage_count + 1, updated_at = ? WHERE skill_hash = ?",
            (datetime.utcnow().isoformat(), skill_hash),
        )
        conn.commit()
        conn.close()

    def stats(self) -> Dict[str, Any]:
        conn = sqlite3.connect(self.db_path)
        total = conn.execute("SELECT COUNT(*) FROM skills").fetchone()[0]
        validated = conn.execute("SELECT COUNT(*) FROM skills WHERE validated = 1").fetchone()[0]
        avg_care = conn.execute("SELECT AVG(care_score) FROM skills").fetchone()[0] or 0
        conn.close()
        return {
            "total_skills": total,
            "validated_skills": validated,
            "pending_validation": total - validated,
            "avg_care_score": round(avg_care, 2),
        }


if __name__ == "__main__":
    lib = SkillLibrary()
    # Ingest a sample skill
    lib.ingest(
        skill_hash="abc123",
        task_type="council_proposal",
        title="Haulage Contract Review",
        description="Standard workflow for reviewing and voting on haulage contracts",
        yaml_body="task_type: council_proposal\nsteps:\n  - Review terms\n  - Check compliance\n  - BFT vote",
        care_score=0.92,
    )
    lib.validate_skill("abc123")
    print("Search 'haulage':", lib.search("haulage"))
    print("Stats:", lib.stats())
